services:
  thought-to-image-simulation-api:
    container_name: thought-to-image-simulation-api
    volumes:
      - ${STIMULUS_IMAGES_DIR}:${STIMULUS_IMAGES_DIR}
    image: evdev3/thought-to-image-simulation-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    restart: unless-stopped
    env_file:
      - .env